/* QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGOCIOS */

/*PRIMEIRO ALGARISMO - OBRIGATORIEDADE
0 - NÃO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDINALIDADE
1- MAXIMO DE UM
N- MAIS DE UM
*/

/* PARA EXCLUIR UMA TABELA */

DROP TABLE CLIENTE;

CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES;

CREATE TABLE CLIENTE(
   IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR(30) NOT NULL,
   SEXO ENUM('M','F') NOT NULL,
   EMAIL VARCHAR (50) UNIQUE,
   CPF VARCHAR (15) UNIQUE
);

SHOW TABLES;

CREATE TABLE ENDERECO(
   IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
   RUA VARCHAR (30) NOT NULL,
   BAIRRO VARCHAR (30) NOT NULL,
   CIDADE VARCHAR (30) NOT NULL,
   ESTADO CHAR (2) NOT NULL,
   ID_CLIENTE INT UNIQUE,
   FOREIGN KEY (ID_CLIENTE)
   REFERENCES CLIENTE (IDCLIENTE)
);


CREATE TABLE TELEFONE (
   IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
   TIPO ENUM ('RES','COM','CEL') NOT NULL,
   NUMERO VARCHAR (10) NOT NULL,
   ID_CLIENTE INT,
   FOREIGN KEY (ID_CLIENTE)
   REFERENCES CLIENTE  (IDCLIENTE)
);

/* ENDERECO - OBRIGATORIO
CADASTRO DE SOMENTE UM,

TELEFONE- NAO OBRIGATORIO
CADASTRO DE MAIS DE UM (OPICIONAL) */

/* 
CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA 
QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERENCIA ENTRE REGISTROS */

/* EM RELACIONAMENTOS 1X1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA CARDINALIDADE N */

INSERT INTO CLIENTE VALUES (NULL,'JOAO','M','JOAO@IG.COM','76458674898');
INSERT INTO CLIENTE VALUES (NULL,'CARLOS','M','CARLOS@IG.COM','09458674898');
INSERT INTO CLIENTE VALUES (NULL,'ANA','F','ANA@IG.COM','9082674898');
INSERT INTO CLIENTE VALUES (NULL,'CLARA','F','NULL','54328674898');
INSERT INTO CLIENTE VALUES (NULL,'JORGE','M','JORGE@IG.COM','34358674898');
INSERT INTO CLIENTE VALUES (NULL,'CELIA','F','CELIA@IG.COM','23258674898');

SELECT * FROM CLIENTE;

+-----------+--------+------+---------------+-------------+
| IDCLIENTE | NOME   | SEXO | EMAIL         | CPF         |
+-----------+--------+------+---------------+-------------+
|         1 | JOAO   | M    | JOAO@IG.COM   | 76458674898 |
|         2 | CARLOS | M    | CARLOS@IG.COM | 09458674898 |
|         3 | ANA    | F    | ANA@IG.COM    | 9082674898  |
|         4 | CLARA  | F    | NULL          | 54328674898 |
|         5 | JORGE  | M    | JORGE@IG.COM  | 34358674898 |
|         6 | CELIA  | F    | CELIA@IG.COM  | 23258674898 |
+-----------+--------+------+---------------+-------------+


INSERT INTO ENDERECO VALUES (NULL,'RUA ANTONIO SA','CENTRO','BELO HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES (NULL,'RUA CAPITARO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES (NULL,'RUA PRES VARGAS','CENTRO','JARDINS','SP',3);
INSERT INTO ENDERECO VALUES (NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES (NULL,'RUA DO OUVIRDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES (NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

SELECT * FROM ENDERECO;


INSERT INTO TELEFONE VALUES (NULL,'CEL','789762531',5);
INSERT INTO TELEFONE VALUES (NULL,'RES','23162531',5);
INSERT INTO TELEFONE VALUES (NULL,'CEL','785662531',1);
INSERT INTO TELEFONE VALUES (NULL,'COM','789762531',2);
INSERT INTO TELEFONE VALUES (NULL,'RES','89762531',1);
INSERT INTO TELEFONE VALUES (NULL,'CEL','754762531',3);
INSERT INTO TELEFONE VALUES (NULL,'CEL','589762531',3);
INSERT INTO TELEFONE VALUES (NULL,'COM','122976251',1);
INSERT INTO TELEFONE VALUES (NULL,'RES','90762531',5);
INSERT INTO TELEFONE VALUES (NULL,'CEL','654762531',2);

SHOW * FROM TELEFONE;

/* SELECAO, PROJECAO E JUNCAO */

/* PROJECAO --> É TUDO O QUE VOCE QUER VER NA TELA */

SELECT NOW () AS DATA_ATUAL;

SELECT 2+2 AS SOMA;

SELECT 2+2 AS SOMA, NOME, NOW()
FROM CLIENTE;

/* SELECAO --> É UM SUBCONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO E O WHERE
*/

SELECT NOME, SEXO, EMAIL /* PROJECAO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELECAO */

SELECT NUMERO /* PROJECAO */
FROM TELEFONE /* ORIGEM */
WHERE TIPO = 'CEL'; /* SELECAO */

/* JUNCAO --> JOIN */

SELECT NOME, EMAIL, IDCLIENTE
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

+--------+---------------+-----------+
| NOME   | EMAIL         | IDCLIENTE |
+--------+---------------+-----------+
| JOAO   | JOAO@IG.COM   |         1 |
| CARLOS | CARLOS@IG.COM |         2 |
| ANA    | ANA@IG.COM    |         3 |
| CLARA  | NULL          |         4 |
| JORGE  | JORGE@IG.COM  |         5 |
| CELIA  | CELIA@IG.COM  |         6 |
+--------+---------------+-----------+


+------------+----------+----------------+
| ID_CLIENTE | BAIRRO   | CIDADE         |
+------------+----------+----------------+
|          4 | CENTRO   | BELO HORIZONTE |
|          1 | CENTRO   | RIO DE JANEIRO |
|          2 | ESTACIO  | RIO DE JANEIRO |
|          6 | FLAMENGO | RIO DE JANEIRO |
|          5 | CENTRO   | VITORIA        |
|          3 | CENTRO   | JARDINS        |
+------------+----------+----------------+



/* NOME,SEXO, BAIRRO, CIDADE */

SELECT NOME,SEXO, BAIRRO, CIDADE /* PROJECAO */
FROM CLIENTE, ENDERECO /* ORIGEM */
WHERE IDCLIENTE = ID_CLIENTE; /*JUNCAO*/

+--------+------+----------+----------------+
| NOME   | SEXO | BAIRRO   | CIDADE         |
+--------+------+----------+----------------+
| JOAO   | M    | CENTRO   | RIO DE JANEIRO |
| CARLOS | M    | ESTACIO  | RIO DE JANEIRO |
| ANA    | F    | CENTRO   | JARDINS        |
| CLARA  | F    | CENTRO   | BELO HORIZONTE |
| JORGE  | M    | CENTRO   | VITORIA        |
| CELIA  | F    | FLAMENGO | RIO DE JANEIRO |
+--------+------+----------+----------------+

SELECT NOME,SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F';

+-------+------+----------+----------------+
| NOME  | SEXO | BAIRRO   | CIDADE         |
+-------+------+----------+----------------+
| ANA   | F    | CENTRO   | JARDINS        |
| CLARA | F    | CENTRO   | BELO HORIZONTE |
| CELIA | F    | FLAMENGO | RIO DE JANEIRO |
+-------+------+----------+----------------+

/* WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F' --> TABELA VERDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE 
JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

+--------+------+----------+----------------+
| NOME   | SEXO | BAIRRO   | CIDADE         |
+--------+------+----------+----------------+
| CLARA  | F    | CENTRO   | BELO HORIZONTE |
| JOAO   | M    | CENTRO   | RIO DE JANEIRO |
| CARLOS | M    | ESTACIO  | RIO DE JANEIRO |
| CELIA  | F    | FLAMENGO | RIO DE JANEIRO |
| JORGE  | M    | CENTRO   | VITORIA        |
| ANA    | F    | CENTRO   | JARDINS        |
+--------+------+----------+----------------+

SELECT NOME, SEXO, BAIRRO, CIDADE /*PROJECAO */
FROM CLIENTE /* ORIGEM*/
INNER JOIN ENDERECO /* JUNCAO */
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO= 'F'; /* SELECAO*/

+-------+------+----------+----------------+
| NOME  | SEXO | BAIRRO   | CIDADE         |
+-------+------+----------+----------------+
| ANA   | F    | CENTRO   | JARDINS        |
| CLARA | F    | CENTRO   | BELO HORIZONTE |
| CELIA | F    | FLAMENGO | RIO DE JANEIRO |
+-------+------+----------+----------------+

/* NOME, SEXO,EMAIL,TIPO,NUMERO */

SELECT NOME, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE , TIPO , NUMERO */

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


+--------+------+---------+----------------+------+-----------+
| NOME   | SEXO | BAIRRO  | CIDADE         | TIPO | NUMERO    |
+--------+------+---------+----------------+------+-----------+
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | CEL  | 785662531 |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | RES  | 89762531  |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | COM  | 122976251 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | COM  | 789762531 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | CEL  | 654762531 |
| JORGE  | M    | CENTRO  | VITORIA        | CEL  | 789762531 |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 23162531  |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 90762531  |
| ANA    | F    | CENTRO  | JARDINS        | CEL  | 754762531 |
| ANA    | F    | CENTRO  | JARDINS        | CEL  | 589762531 |
+--------+------+---------+----------------+------+-----------+

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;


+--------+------+---------+----------------+------+-----------+
| NOME   | SEXO | BAIRRO  | CIDADE         | TIPO | NUMERO    |
+--------+------+---------+----------------+------+-----------+
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | CEL  | 785662531 |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | RES  | 89762531  |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | COM  | 122976251 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | COM  | 789762531 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | CEL  | 654762531 |
| JORGE  | M    | CENTRO  | VITORIA        | CEL  | 789762531 |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 23162531  |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 90762531  |
| ANA    | F    | CENTRO  | JARDINS        | CEL  | 754762531 |
| ANA    | F    | CENTRO  | JARDINS        | CEL  | 589762531 |
+--------+------+---------+----------------+------+-----------+




/*
   DML - DATA MANIPULATION LANGUAGE
   DDL - DATA DEFENITION LANGUAGE
   DCL - DATA CONTROL LANGUAGE
   TCL - TRANSACION CONTROL LANGUAGE


*/

/* INSERT  (DML)*/

INSERT INTO CLIENTE VALUES (NULL,'PAULA','M',NULL,'778742733');

INSERT INTO ENDERECO VALUES (NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ', 7);

SELECT * FROM CLIENTE;

/* FILTROS (DML)*/

SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/* UPDATE (DML) */


SELECT * FROM CLIENTE
WHERE IDCLIENTE= 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE= 7;

/* DELETE (DML) */


INSERT INTO CLIENTE VALUES (NULL,'XXX','M',NULL,'XX');

DELETE FROM CLIENTE 
WHERE IDCLIENTE = 9;

/* DDL - DATA DEFENITION LANGUAGE

*/

CREATE TABLE PRODUTO (
  IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(30) NOT NULL,
  PRECO INT,
  FRETE FLOAT (10,2) NOT NULL
);


/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */


ALTER TABLE PRODUTO 
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

+----------------+-------------+------+-----+---------+----------------+
| Field          | Type        | Null | Key | Default | Extra          |
+----------------+-------------+------+-----+---------+----------------+
| IDPRODUTO      | int(11)     | NO   | PRI | NULL    | auto_increment |
| NOME_PRODUTO   | varchar(30) | NO   |     | NULL    |                |
| VALOR_UNITARIO | int(11)     | NO   |     | NULL    |                |
| FRETE          | float(10,2) | NO   |     | NULL    |                |
+----------------+-------------+------+-----+---------+----------------+

ALTER TABLE PRODUTO 
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;


+----------------+-------------+------+-----+---------+----------------+
| Field          | Type        | Null | Key | Default | Extra          |
+----------------+-------------+------+-----+---------+----------------+
| IDPRODUTO      | int(11)     | NO   | PRI | NULL    | auto_increment |
| NOME_PRODUTO   | varchar(30) | NO   |     | NULL    |                |
| VALOR_UNITARIO | int(11)     | YES  |     | NULL    |                |
| FRETE          | float(10,2) | NO   |     | NULL    |                |
+----------------+-------------+------+-----+---------+----------------+




/* MODIFY - ALTERANDO O TIPO*/

ALTER TABLE PRODUTO 
MODIFY VALOR_UNITARIO VARCHAR (50) NOT NULL;


DESC PRODUTO;

/* ADICIONANDO COLUNAS */

ALTER TABLE PRODUTO 
ADD PESO FLOAT (10,2) NOT NULL;

/* APAGANDO UMA COLUNA */

ALTER TABLE PRODUTO 
DROP COLUMN PESO;

DESC PRODUTO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESECIFICA */


ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT (10,2) NOT NULL
AFTER NOME_PRODUTO;

DESC PRODUTO;

ALTER TABLE PRODUTO 
DROP COLUMN PESO;


ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT (10,2) NOT NULL
FIRST;


/* DROP DATABASE ... */


 CLIENTE 

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');


  ENDERECO

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',14);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',15);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',16);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',17);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',18);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',19);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',22);


 TELEFONE 

INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);
INSERT INTO TELEFONE VALUES(NULL,'CEL','44522578',21);


/* RELATORIO GERAL DE TODOS OS CLIENTES */

DESC CLIENTE;

DESC ENDERECO;

DESC TELEFONE;

SELECT  C.IDCLIENTE, C.NOME, C.SEXO , C.EMAIL, C.CPF, 
        E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
        T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/* RELATORIO DE HOMENS */

SELECT C.NOME, C.SEXO , C.EMAIL, C.CPF, 
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
       T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

/* ID  19,20,13,15 F / 17 M (ALTERANDO O SEXO )*/

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 19
OR IDCLIENTE = 15
OR IDCLIENTE = 20
OR IDCLIENTE = 13;

SELECT * FROM CLIENTE 
WHERE IDCLIENTE IN (19,15,20,13); 


UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE IN (19,15,20,13);


/* RELATORIO DE MULHERES */

SELECT C.NOME, C.SEXO , C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

UPDATE CLIENTE SET SEXO ='M'
WHERE IDCLIENTE = 17;


/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*) AS QUANTIDADE, SEXO
FROM CLIENTE 
GROUP BY SEXO;


/* IDS E EMAIL DE MULHERES QUE MOREM NO CENTRO DO RIO E 
NAO TENHAM CELULAR */ 


SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INENTRO' NER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND BAIRRO = 'C
AND CIDADE =  'RIO DE JANEIRO'
AND (TIPO = 'CEL' OR 'RES');


/* PARA UMA CAMPANHA DE MARKETING O SETOR SOLICITOU UM RELATORIO COM O NOME,
EMAIL E TELEFONE CELULAR DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCE TERA QUE PASSAR A QUERY PARA GERAR O REALATORIO PARA O PROGAMADOR */


SELECT   C.NOME, C.EMAIL,T.NUMERO AS CELULAR 
FROM CLIENTE C /* ORIGEM */
INNER JOIN ENDERECO E /* JUNCAO CONDICAO */
ON C.IDCLIENTE = E.ID_CLIENTE /* JUNCAO CONDICAO */
INNER JOIN TELEFONE T /* JUNCAO */
ON C.IDCLIENTE = T.ID_CLIENTE /* JUNCAO CONDICAO */
WHERE ESTADO =  'RJ' /* SELECAO */
AND TIPO = 'CEL'; /* SELECAO */


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATORIO COM O NOME,
EMAIL E TELEFONE CELULAR DAS MULHERES QUE MORAM NO ESTADO DE SAO PAULO
VOCE TERA QUE PASSAR A QUERY PARA GERAR O REALATORIO PARA O PROGAMADOR */   


SELECT  C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND ESTADO = 'SP';


/* NOME, EMAIL , NUMERO , ESTADO */

SELECT C.NOME, C.EMAIL , E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;


+---------+-------------------+--------+-----------+
| NOME    | EMAIL             | ESTADO | NUMERO    |
+---------+-------------------+--------+-----------+
| JORGE   | JORGE@IG.COM      | ES     | 789762531 |
| JORGE   | JORGE@IG.COM      | ES     | 23162531  |
| JOAO    | JOAO@IG.COM       | RJ     | 785662531 |
| CARLOS  | CARLOS@IG.COM     | RJ     | 789762531 |
| JOAO    | JOAO@IG.COM       | RJ     | 89762531  |
| ANA     | ANA@IG.COM        | SP     | 754762531 |
| ANA     | ANA@IG.COM        | SP     | 589762531 |
| JOAO    | JOAO@IG.COM       | RJ     | 122976251 |
| JORGE   | JORGE@IG.COM      | ES     | 90762531  |
| CARLOS  | CARLOS@IG.COM     | RJ     | 654762531 |
| ANDRE   | ANDRE@GLOBO.COM   | RJ     | 33567765  |
| ANDRE   | ANDRE@GLOBO.COM   | RJ     | 88668786  |
| ANDRE   | ANDRE@GLOBO.COM   | RJ     | 55689654  |
| GIOVANA | NULL              | RJ     | 88687979  |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88965676  |
| LORENA  | NULL              | RJ     | 89966809  |
| EDUARDO | NULL              | PR     | 88679978  |
| ANTONIO | ANTONIO@IG.COM    | SP     | 99655768  |
| ANTONIO | ANTONIO@UOL.COM   | PR     | 89955665  |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 77455786  |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 89766554  |
| CARMEM  | CARMEM@IG.COM     | RJ     | 77755785  |
| CARMEM  | CARMEM@IG.COM     | RJ     | 44522578  |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 44522578  |
+---------+-------------------+--------+-----------+



SELECT C.NOME, 
       IFNULL (C.EMAIL,'NAO TEM EMAIL'),
       E.ESTADO, 
       T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;


+---------+----------------------------------+--------+-----------+
| NOME    | IFNULL (C.EMAIL,'NAO TEM EMAIL') | ESTADO | NUMERO    |
+---------+----------------------------------+--------+-----------+
| JORGE   | JORGE@IG.COM                     | ES     | 789762531 |
| JORGE   | JORGE@IG.COM                     | ES     | 23162531  |
| JOAO    | JOAO@IG.COM                      | RJ     | 785662531 |
| CARLOS  | CARLOS@IG.COM                    | RJ     | 789762531 |
| JOAO    | JOAO@IG.COM                      | RJ     | 89762531  |
| ANA     | ANA@IG.COM                       | SP     | 754762531 |
| ANA     | ANA@IG.COM                       | SP     | 589762531 |
| JOAO    | JOAO@IG.COM                      | RJ     | 122976251 |
| JORGE   | JORGE@IG.COM                     | ES     | 90762531  |
| CARLOS  | CARLOS@IG.COM                    | RJ     | 654762531 |
| ANDRE   | ANDRE@GLOBO.COM                  | RJ     | 33567765  |
| ANDRE   | ANDRE@GLOBO.COM                  | RJ     | 88668786  |
| ANDRE   | ANDRE@GLOBO.COM                  | RJ     | 55689654  |
| GIOVANA | NAO TEM EMAIL                    | RJ     | 88687979  |
| KARLA   | KARLA@GMAIL.COM                  | RJ     | 88965676  |
| LORENA  | NAO TEM EMAIL                    | RJ     | 89966809  |
| EDUARDO | NAO TEM EMAIL                    | PR     | 88679978  |
| ANTONIO | ANTONIO@IG.COM                   | SP     | 99655768  |
| ANTONIO | ANTONIO@UOL.COM                  | PR     | 89955665  |
| ELAINE  | ELAINE@GLOBO.COM                 | SP     | 77455786  |
| ELAINE  | ELAINE@GLOBO.COM                 | SP     | 89766554  |
| CARMEM  | CARMEM@IG.COM                    | RJ     | 77755785  |
| CARMEM  | CARMEM@IG.COM                    | RJ     | 44522578  |
| ADRIANA | ADRIANA@GMAIL.COM                | RJ     | 44522578  |
+---------+----------------------------------+--------+-----------+



SELECT C.NOME, 
       IFNULL (C.EMAIL,'NAO TEM EMAIL') AS 'EMAIL',
       E.ESTADO, 
       T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;


+---------+-------------------+--------+-----------+
| NOME    | EMAIL             | ESTADO | NUMERO    |
+---------+-------------------+--------+-----------+
| JORGE   | JORGE@IG.COM      | ES     | 789762531 |
| JORGE   | JORGE@IG.COM      | ES     | 23162531  |
| JOAO    | JOAO@IG.COM       | RJ     | 785662531 |
| CARLOS  | CARLOS@IG.COM     | RJ     | 789762531 |
| JOAO    | JOAO@IG.COM       | RJ     | 89762531  |
| ANA     | ANA@IG.COM        | SP     | 754762531 |
| ANA     | ANA@IG.COM        | SP     | 589762531 |
| JOAO    | JOAO@IG.COM       | RJ     | 122976251 |
| JORGE   | JORGE@IG.COM      | ES     | 90762531  |
| CARLOS  | CARLOS@IG.COM     | RJ     | 654762531 |
| ANDRE   | ANDRE@GLOBO.COM   | RJ     | 33567765  |
| ANDRE   | ANDRE@GLOBO.COM   | RJ     | 88668786  |
| ANDRE   | ANDRE@GLOBO.COM   | RJ     | 55689654  |
| GIOVANA | NAO TEM EMAIL     | RJ     | 88687979  |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88965676  |
| LORENA  | NAO TEM EMAIL     | RJ     | 89966809  |
| EDUARDO | NAO TEM EMAIL     | PR     | 88679978  |
| ANTONIO | ANTONIO@IG.COM    | SP     | 99655768  |
| ANTONIO | ANTONIO@UOL.COM   | PR     | 89955665  |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 77455786  |
| ELAINE  | ELAINE@GLOBO.COM  | SP     | 89766554  |
| CARMEM  | CARMEM@IG.COM     | RJ     | 77755785  |
| CARMEM  | CARMEM@IG.COM     | RJ     | 44522578  |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 44522578  |
+---------+-------------------+--------+-----------+


/* VIEW */

SELECT C.NOME, 
       C.SEXO, 
       C.EMAIL, 
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

CREATE VIEW RELATORIO AS 
SELECT C.NOME, 
       C.SEXO, 
       C.EMAIL, 
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;


SELECT * FROM RELATORIO;


SHOW TABLES; /* MOSTRA A VIEW CRIADA */
SHOW DATABASES;
SHOW VIEW; /* NAO EXISTE*/


DROP VIEW RELATORIO;

/* INSERINDO UM PREFIXO */


CREATE VIEW V_RELATORIO AS 
SELECT C.NOME, 
       C.SEXO, 
       IFNULL (C.EMAIL, 'NAO TEM EMAIL') AS EMAIL,
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

'UTILIZAR UM PREFIXO PARA FICAR MAIS FACIL PARA VERIFICAR'


/* UPDATE, INSERT E DELETE - DML */

INSERT INTO V_RELATORIO VALUES (
'ANDREIA','F', 'ANDREIA@UOL.COM.BR','CEL', '897265327','CENTRO','VITORIA', 'ES'
); /* VIEW QUANDO TEM JOIN NAO DA PRA INCLUIR DADOS */

DELETE FROM V_RELATORIO
WHERE NOME = 'JORGE'; /* VIEW QUANDO TEM JOIN NAO DA PRA DELETAR */


UPDATE V_RELATORIO 
SET NOME = 'JOSE'
WHERE NOME = 'JORGE'; /* PERMITIDO FAZER UPDATE EM JOIN */



CREATE TABLE JOGADORES(
    IDJOGADOR INT,
    NOME VARCHAR (30),
    ESTADO CHAR (2)

);

INSERT INTO JOGADORES VALUES (1,'GUERRERRO','RS');
INSERT INTO JOGADORES VALUES (2,'GABIGOL','RJ');
INSERT INTO JOGADORES VALUES (3,'GANSO','RJ');
INSERT INTO JOGADORES VALUES (4,'NENEO','RJ');
INSERT INTO JOGADORES VALUES (5,'LOVE', 'SP');

CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;

SELECT * FROM V_JOGADORES;

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERRO';

SELECT * FROM V_JOGADORES;

INSERT INTO V_JOGADORES VALUES ('GUERRERRO','RS');

/* ORDER BY --> ORDENE POR */


CREATE TABLE ALUNOS (
   NUMERO INT,
   NOME VARCHAR (30)
);


INSERT INTO ALUNOS VALUES (1,'JOAO');
INSERT INTO ALUNOS VALUES (1,'MARIA');
INSERT INTO ALUNOS VALUES (2,'ZOE');
INSERT INTO ALUNOS VALUES (2,'ANDRE');
INSERT INTO ALUNOS VALUES (3,'CLARA');
INSERT INTO ALUNOS VALUES (1,'CLARA');
INSERT INTO ALUNOS VALUES (1,'MAFRA');
INSERT INTO ALUNOS VALUES (5,'JANAINA');
INSERT INTO ALUNOS VALUES (1,'JANAINA');
INSERT INTO ALUNOS VALUES (3,'MARCELO');
INSERT INTO ALUNOS VALUES (4,'GIOVANNI');
INSERT INTO ALUNOS VALUES (5,'ANTONIO');
INSERT INTO ALUNOS VALUES (6,'ANA');
INSERT INTO ALUNOS VALUES (6,'VIVIANE');

SELECT * FROM ALUNOS;
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1; (ORDENE PELA PRIMEIRA COLUNA)

SELECT * FROM ALUNOS
ORDER BY 2; (POR ORDEM PELA SEGUNDA COLUNA)


/* ORDENANDO POR MAIS DE UMA COLUNA */

SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;

=

SELECT * FROM ALUNOS
ORDER BY 1,2;

/* MESCLANDO ORDER BY COM PROJECAO */

SELECT NOME FROM ALUNOS
ORDER BY NUMERO, NOME; (IR SEMPRE PELO NOME)

/* ORDER BY DESC = DESCENDENTE (DECRESCENTE) / ASC = ASCENDENTE (CRESCENTE) */



SELECT * FROM ALUNOS
ORDER BY 1,2;

SELECT * FROM ALUNOS
ORDER BY 1 ASC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC;


SELECT * FROM ALUNOS
ORDER BY 1,2 DESC;

SELECT * FROM ALUNOS
ORDER BY 1 DESC,2 DESC; 


/* ORDENANDO COM JOIN */

 
SELECT C.NOME, 
       C.SEXO, 
       IFNULL (C.EMAIL, 'NAO TEM EMAIL') AS EMAIL,
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 2;

SHOW TABLES;

SELECT * FROM V_RELATORIO
ORDER BY 1;

/* DELIMITADOR */

STATUS

DELIMITER $ (SAINDO E VOLTANDO O DELIMITADOR VOLTA PARA O ORIGINAL)

SELECT * FROM V_RELATORIO;

DELIMITER $

/* STORED PROCEDURES */













































































































































































